name: FastAPI
channels:
  - defaults
dependencies:
  - bzip2=1.0.8=h2bbff1b_5
  - ca-certificates=2024.3.11=haa95532_0
  - libffi=3.4.4=hd77b12b_0
  - openssl=1.1.1w=h2bbff1b_0
  - pip=23.3.1=py311haa95532_0
  - python=3.11.0=h966fe2a_3
  - setuptools=68.2.2=py311haa95532_0
  - sqlite=3.41.2=h2bbff1b_0
  - tk=8.6.12=h2bbff1b_0
  - tzdata=2024a=h04d1e81_0
  - vc=14.2=h21ff451_1
  - vs2015_runtime=14.27.29016=h5e58377_2
  - wheel=0.41.2=py311haa95532_0
  - xz=5.4.6=h8cc25b3_0
  - zlib=1.2.13=h8cc25b3_0
  - pip:
      - annotated-types==0.6.0
      - anyio==4.3.0
      - certifi==2024.2.2
      - click==8.1.7
      - dnspython==2.6.1
      - email-validator==2.1.1
      - fastapi==0.110.0
      - greenlet==3.0.3
      - h11==0.14.0
      - httpcore==1.0.4
      - httptools==0.6.1
      - httpx==0.27.0
      - idna==3.6
      - itsdangerous==2.1.2
      - jinja2==3.1.3
      - markupsafe==2.1.5
      - orjson==3.9.15
      - psycopg2==2.9.9
      - pydantic==2.6.4
      - pydantic-core==2.16.3
      - pydantic-extra-types==2.6.0
      - pydantic-settings==2.2.1
      - python-dotenv==1.0.1
      - python-multipart==0.0.9
      - pyyaml==6.0.1
      - sniffio==1.3.1
      - sqlalchemy==2.0.32
      - starlette==0.36.3
      - typing-extensions==4.10.0
      - ujson==5.9.0
      - uvicorn==0.29.0
      - watchfiles==0.21.0
      - websockets==12.0
prefix: C:\Users\dldls\anaconda3\envs\FastAPI
